### ISSUE TITLE
Improve HTML version formatting

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/books#36]
Modify this:

```css
body {
    font-size: 125%;
}
pre {
    background: rgb(233, 233, 233);
    padding: 15px 20px;
    border-radius: 10px;
    font-size: 0.875em;
}
```
